version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: plagiarism_detector
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres/plagiarism_detector
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN}
      VK_GROUP_TOKEN: ${VK_GROUP_TOKEN}
      VK_APP_ID: ${VK_APP_ID}
      VK_APP_SECRET: ${VK_APP_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      VK_PAY_MERCHANT_ID: ${VK_PAY_MERCHANT_ID}
      VK_PAY_SECRET_KEY: ${VK_PAY_SECRET_KEY}
      DEBUG: ${DEBUG:-False}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/__pycache__

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: 